language: java

jdk: 
  - openjdk7
  - oraclejdk7

script:
  - ./gradlew check
# compile and execute unit-tests
  - ./gradlew test
deploy:
    provider: heroku
    api_key: b1bb5055-8428-48bd-a455-e37423cde6f8
