/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dagur13' at '10/27/14 12:42 PM' with Gradle 2.1
 *
 * @author dagur13, @date 10/27/14 12:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
